authors/urls.py
from django.urls import path

from authors import views

app_name = 'authors'

urlpatterns = [
    path('login/', views.AuthorsLogin.as_view(), name='login'),
    path('logout/', views.AuthorsLogout.as_view(), name='logout'),

    path('register/', views.AuthorsRegister.as_view(), name='register'),
    path('feed/', views.AuthorsFeed.as_view(), name='feed'),
    path('search/', views.AuthorsSearch.as_view(), name='search'),
    path('profile/<int:pk>', views.ProfilePage.as_view(), name='profile'),
    path('followers/<int:pk>/<str:action>',
         views.ProfileFollowMethods.as_view(), name='followers')
]

posts/urls.py
from django.urls import path

from posts import views

app_name = 'posts'

urlpatterns = [
    path('post/', views.PostsView.as_view(), name='post'),
    path('post/<int:pk>', views.PostsView.as_view(), name='post'),
    path('delete_tweet/<int:pk>', views.PostDelete.as_view(), name='delete'),
    path('add_comment/<int:pk>', views.CommentView.as_view(), name='add_comment')
]

twitter/urls.py
from django.contrib import admin
from django.urls import include, path

from posts.views import PostList

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authors/', include('authors.urls')),
    path('posts/', include('posts.urls')),
    path('', PostList.as_view(), name='home'),
]

templates/global/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
{% include "global/partials/head.html" %}
<body class="background-body ">
    {% include "global/partials/header.html" %}
    {% include "global/partials/messages.html" %}
    {% block content %}{% endblock content %}
</body>
</html>

templates/global/partials/form.html
<div class="main-content container p-2 rounded text-center  ">
    <div class="row mb-3">
        {% if title %}
            <h3 class="card-text-color">{{title}}</h3>
        {% endif %}
    </div>


    <form class="container m-auto d-flex flex-column gap-2 align-items-center card-text-color" action="{{form_action}}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {% for field in form %}
        <div data-mdb-input-init class="row  text-center mx-2">
            <label class="d-none" for="{{field.id_for_label}}">{{field.label}}</label>
            {{field}}
        </div>
        
        {% for error in field.errors %}
            <div class="row">
                <div class="font-small form-error text-center m-auto">
                    {{error}}
                </div>
            </div>
                {%empty%}
                {% if field.help_text %}
                    <p class='small'>{{field.help_text}}</p>
                {% endif %}
                {% endfor %}


            {% endfor %}


        <div class="form-content form-content-grid">
            <div class="form-group">
                <button class="btn btn-success mt-1" type="submit">{{ btn_text}}</button>
            </div>
        </div>

    </form>
</div>

templates/global/partials/head.html
{% load static %}

<head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100..900&display=swap" rel="stylesheet">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="{% static "global/css/global.css" %}">


    <title>Twitter</title>
</head>

templates/global/partials/header.html
<header class=' mb-1 px-3'>
    <div class="row center-items p-1">
        <div class="col-12 col-sm-4 text-center mt-2">
            <h1><a id="logo" href="{% url "home" %}">Twitter</a></h1>
        </div>
        <div class="col-8 col-sm-4 col-md-6">
            <form action="{% url "authors:search" %}" method="POST" class="form-group d-flex justify-content-between">
            {% csrf_token %}
            <input type="text" placeholder="Buscar usuário..." name="search_term" class="form-control w-100" >
            <button class="btn-search" type="submit">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                    <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
                </svg>
            </button>
        </form>
        </div>
        <div class="col-4 col-sm-4 col-md-2 text-end p-1">
            {% if user.is_authenticated %}
            <div class="row">
                <div class="col-6 col-sm-6 p-0 d-flex justify-content-end align-items-center">
                    <a class="btn btn-primary border border-primary p-1 rounded my-auto" href="{% url "authors:feed" %}">Feed</a>
                </div>
                <div class="col-6 col-sm-6 p-0 d-flex justify-content-center align-items-center">
                <form class="form-group text-end m-1" action="{% url "authors:logout" %}" method='POST'>
                    {% csrf_token %}
                    <input type="hidden" name="username" value="{{request.user.username}}">
                    <button class="btn btn-danger p-1 border border-danger rounded " type="submit">Sair</button>
                </form>
                </div>
            </div>
                
            {% else %}
            <div class="card-text-color">
                <a class="btn-log" href="{% url "authors:login" %}">Entre</a> ou    <a class="btn-log" href="{% url "authors:register" %}">Cadastre-se</a>
            </div>
        {% endif %}
        </div>
    </div>
</header>

templates/global/partials/messages.html
{% if messages %}
    <div class="container mt-3">
        {% for message in messages %}
            <div class="row">
                <div class="col-11 col-sm-10 col-md-6 mx-auto  message {{message.tags}}">

                    {{ message }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endif %}