authors/urls.py
from django.urls import path

from authors import views

app_name = 'authors'

urlpatterns = [
    path('login/', views.AuthorsLogin.as_view(), name='login'),
    path('logout/', views.AuthorsLogout.as_view(), name='logout'),

    path('register/', views.AuthorsRegister.as_view(), name='register'),
    path('feed/', views.AuthorsFeed.as_view(), name='feed'),
    path('search/', views.AuthorsSearch.as_view(), name='search'),
    path('profile/<int:pk>', views.ProfilePage.as_view(), name='profile'),
    path('followers/<int:pk>/<str:action>',
         views.ProfileFollowMethods.as_view(), name='followers')
]

posts/urls.py
from django.urls import path

from posts import views

app_name = 'posts'

urlpatterns = [
    path('post/', views.PostsView.as_view(), name='post'),
    path('post/<int:pk>', views.PostsView.as_view(), name='post'),
    path('delete_tweet/<int:pk>', views.PostDelete.as_view(), name='delete'),
    path('add_comment/<int:pk>', views.CommentView.as_view(), name='add_comment')
]

twitter/urls.py
from django.contrib import admin
from django.urls import include, path

from posts.views import PostList

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authors/', include('authors.urls')),
    path('posts/', include('posts.urls')),
    path('', PostList.as_view(), name='home'),
]

authors/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    author = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True, null=True)
    following = models.ManyToManyField(
        'self', blank=True, symmetrical=False, related_name='seguidores')

    def __str__(self):
        return self.author.username

authors/forms.py
import re
from django import forms  # type: ignore
from django.contrib.auth.models import User

from utils.utils_form import add_placeholder


def strong_password(password):
    regex = re.compile(r'^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).{8,}$')

    if not regex.match(password):
        raise forms.ValidationError((
            'A senha deve possuir, pelo menos, 8 caracteres sendo '
            'ao menos uma letra maiúscula, uma minúscula e um número.'),
            code='invalid'
        )


class LoginForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields['username'], 'Nome de usuário')
        add_placeholder(self.fields['password'], 'Senha')

    username = forms.CharField(
        label='Nome de usuário',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control'}),
        label="Senha",
    )


class RegisterForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields['username'], 'Nome de usuário')
        add_placeholder(self.fields['email'], 'E-mail')
        add_placeholder(self.fields['password'], 'Senha')
        add_placeholder(self.fields['password2'], 'Confirme sua senha')

    username = forms.CharField(
        required=True,
        label='Nome de usuário',
        help_text='Deve conter entre 4 e 150 caracteres.',
        error_messages={
            'required': 'Campo obrigatório.',
            'min_length': 'Deve conter pelo menos 4 caracteres.',
            'max_length': 'Deve conter, no máximo, 150 caracteres.',
            'unique': 'Nome de usuário não disponível.'

        },

        min_length=4,
        max_length=150
    )

    email = forms.EmailField(
        error_messages={
            'required': 'Campo obrigatório.',
            'invalid': 'Deve ser um e-mail válido.',
        },
        required=True,
        label='E-mail',
    )

    password = forms.CharField(
        widget=forms.PasswordInput(),
        required=True,
        error_messages={
            'required': 'Campo obrigatório.'
        },
        help_text='A senha deve possuir, pelo menos, 8 caracteres sendo '
        'ao menos uma letra maiúscula, uma minúscula e um número.',
        validators=[strong_password],

        label='Senha'
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(),
        required=True,
        label='Confirme sua senha',
        error_messages={
            'required': 'Campo obrigatório.'
        },

    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

    def clean_email(self):
        email = self.cleaned_data.get('email', '')
        exists = User.objects.filter(email=email).exists()

        if exists:
            raise forms.ValidationError(
                'E-mail já cadastrado.', code='invalid',
            )

        return email

    def clean(self):
        cleaned_data = super().clean()

        password = cleaned_data.get('password')
        password2 = cleaned_data.get('password2')

        if password != password2:

            password_confirmation_error = forms.ValidationError(
                "As senhas devem ser iguais.",
                code='invalid'
            )

            raise forms.ValidationError(
                {

                    'password2': [password_confirmation_error]
                }
            )

authors/views.py
from django.db.models import Q
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import View
from django.views.generic import ListView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from authors.forms import LoginForm, RegisterForm
from authors.models import Profile
from posts.forms import PostForm
from posts.models import Tweet
# Create your views here.


class AuthorsLogin(View):
    def get(self, request):
        if request.method != 'GET':
            messages.error(request, 'Requisição inválida.')
            return redirect('home')

        form = LoginForm()

        return render(
            request,
            'authors/pages/login.html',

            context={
                'form': form,
                'form_action': reverse('authors:login'),
                'btn_text': 'Entrar'
            })

    def post(self, request):
        if not request.POST:
            raise Http404()

        form = LoginForm(request.POST)

        if form.is_valid():
            authenticate_user = authenticate(
                username=form.cleaned_data.get('username', ''),
                password=form.cleaned_data.get('password', '')
            )

        if authenticate_user is not None:
            login(request, authenticate_user)
            messages.success(request, "Login feito com sucesso")
            return redirect(reverse('authors:feed'))
        messages.error(request, "Credenciais não autorizadas.")
        return redirect(reverse('authors:login'))


@method_decorator(
    login_required(
        login_url='authors:login',
        redirect_field_name='next'), name='dispatch')
class AuthorsLogout(View):
    def post(self, request):
        if not request.POST:
            messages.error(request, 'Requisição inválida.')
            return redirect('home')

        if request.POST.get('username') != request.user.username:
            messages.error(request, 'Requisição inválida.')
            return redirect(reverse('authors:feed'))
        logout(request)
        messages.success(request, 'Logout feito com sucesso.')

        return redirect(reverse('authors:login'))


class AuthorsRegister(View):
    def get(self, request):
        if request.method != 'GET':
            messages.error(request, 'Requisição inválida.')
            return redirect('home')

        register_form_data = request.session.get(
            'register_form_data', None)
        form = RegisterForm(register_form_data)

        return render(
            request,
            'authors/pages/register.html',
            context={
                'form': form,
                'form_action': reverse('authors:register'),
                'btn_text': 'Cadastrar'
            })

    def post(self, request):
        if not request.POST:
            messages.error(request, 'Requisição inválida.')
            return redirect('home')

        POST = request.POST
        request.session['register_form_data'] = POST
        form = RegisterForm(POST)

        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()

            del (request.session['register_form_data'])
            messages.success(request, 'Usuário cadastrado com sucesso.')
            return redirect('authors:login')

        messages.error(request, 'Existem erros no formulário.')
        return redirect('authors:register')


@method_decorator(
    login_required(
        login_url='authors:login',
        redirect_field_name='next'), name='dispatch')
class AuthorsFeed(ListView):
    model = Tweet
    context_object_name = 'tweets'

    ordering = ['created_at']

    def get_queryset(self, *args, **kwargs):
        current_user = self.request.user
        current_profile = Profile.objects.filter(author=current_user).first()

        tweets = Tweet.objects.filter(
            author__in=current_profile.following.all())
        return tweets

    def get(self, request):
        if request.method != 'GET':
            messages.error(request, 'Requisição inválida.')
            return redirect('home')

        tweets = self.get_queryset()
        form = PostForm()
        return render(
            request,
            'authors/pages/feed.html',
            context={
                'tweets': tweets,
                'form': form,
                'btn_text': 'Tweet',
                'form_action': reverse('posts:post'),
            }
        )


class AuthorsSearch(ListView):
    model = Profile
    context_object_name = 'profiles'
    ordering = ['Profile.author.user.username']

    def post(self, request, *args, **kwargs):
        if request.method != 'POST':
            messages.error(request, 'Requisição inválida.')
            return redirect('home')

        search_term = request.POST.get('search_term', '')

        usuarios = Profile.objects.filter(
            Q(author__username__icontains=search_term)
        )
        return render(
            request,
            template_name='authors/pages/search.html',
            context={
                'search_term': search_term,
                'usuarios': usuarios
            }
        )


class ProfilePage(ListView):
    model = Tweet

    def get(self, request, pk):
        if request.method != 'GET':
            messages.error(request, 'Requisição inválida.')
            return redirect('home')

        tweets = Tweet.objects.filter(author__id=pk)
        profile_from_page = Profile.objects.get(author__id=pk)
        btn_text = ''
        btn_action = ''
        logged = False

        if request.user.is_authenticated:
            logged = True
            current_user_profile = Profile.objects.get(
                author__username=request.user.username)
            if current_user_profile.following.filter(id=profile_from_page.id).exists():
                btn_text = 'Deixar de seguir'
                btn_action = 'unfollow'
            else:
                btn_text = 'Seguir'
                btn_action = 'follow'
            return render(
                request,
                'authors/pages/profile.html',
                context={
                    'tweets': tweets,
                    'logged': logged,
                    'profile': profile_from_page,
                    'btn_text': btn_text,
                    'btn_action': reverse(
                        'authors:followers',
                        kwargs={
                            'pk': profile_from_page.id,
                            'action': btn_action})
                }
            )
        return render(
            request,
            'authors/pages/profile.html',
            context={
                'tweets': tweets,
                'logged': logged,
                'profile': profile_from_page,

            }
        )


class ProfileFollowMethods(View):
    def get(self, request, action,  pk):
        if request.method != 'GET':
            messages.error(request, 'Requisição inválida.')
            return redirect('home')

        current_user_logged = Profile.objects.filter(
            author__username=request.user.username).first()

        to_follow_profile = Profile.objects.filter(id=pk).first()

        if action == 'follow':
            current_user_logged.following.add(to_follow_profile.id)
            messages.success(request, f'Seguindo @{to_follow_profile}.')
        elif action == 'unfollow':
            current_user_logged.following.remove(to_follow_profile.id)
            messages.warning(
                request, f'Deixou de seguir @{to_follow_profile}.')

        return redirect(request.META.get("HTTP_REFERER"))

authors/templates/authors/pages/feed.html
{% extends "global/partials/base.html" %}
{% block content %}
<div class="container p-2">
    <div class="row">
        <h4 class="text-center my-3 card-text-color">Olá, @{{user.username}}</h4>
    </div>
    <div class="row text-center">
        <div class="col-6 col-sm-6 col-md-4 col-lg-3 mx-auto">

            <a class=" btn btn-primary" href="{% url "authors:profile" user.id %}">
                Seus tweets
            </a>
        </div>
    </div>
    <div class="m-3">
        {% include "global/partials/form.html" %}

    </div>
        <div class="row">
        <div class="col-6 col-sm-6 mx-auto card-text-color ">
            <h4 class="text-center">Publicações seguidas</h4>
        </div>
    </div>
    {% for tweet in tweets %}
        {% include "authors/partials/card.html" %}
    {%empty%}
        <div class="row">
            <div class="col-6 col-sm-6 text-center mx-auto card-text-color border border-warning p-2 m-2 ">
                <span>Nenhum tweet encontrado...</span>
            </div>
        </div>
    {% endfor %}

</div>
{% endblock content %}

authors/templates/authors/pages/login.html
{% extends "global/partials/base.html" %}

{% block content %}

    <div class="container d-flex flex-column gap-2 justify-content-center">

        {% if user.username %}
            Você está logado como {{user.username}}

        {% else %}
            <div class="container d-flex flex-column gap-2 justify-content-center align-items-center mt-5">

                {% include "global/partials/form.html" with title="Login" %}

                <a class="border border-success btn btn-primary" href="{% url "authors:register" %}">Não possui uma conta?</a>
            </div>
        {% endif %}
    </div>
    
    
{% endblock content %}

authors/templates/authors/pages/profile.html
{% extends "global/partials/base.html" %}

{% block content %}

<div class="container">
    <div class="d-flex justify-content-around my-4">
        <h3 class="card-text-color">
            {% if user.username == profile.author.username  %}
                Seus tweets
            {% else %}
                Perfil de @{{profile.author.username}}
            {% endif %}
        </h3>

        {% if logged %}
            {% if user.username != profile.author.username %}
                <form action="{{btn_action}}">
                    {% csrf_token %}
                    <button class="btn btn-primary" type="submit">{{btn_text}}</button>
                </form>
            {% endif %}
        {% endif %}
    </div>

    <ul>
        {% for tweet in tweets %}
            {% include "authors/partials/card.html" %}
            {%empty%}
        <div class="row">
            <div class="col-6 col-sm-6 text-center mx-auto card-text-color border border-warning p-2 m-2 ">
                <span>Nenhum tweet encontrado...</span>
            </div>
        </div>
        {% endfor %}
    </ul>

</div>

{% endblock content %}

authors/templates/authors/pages/register.html
{% extends "global/partials/base.html" %}

{% block content %}

    <div class="container d-flex flex-column gap-2 justify-content-center align-items-center mt-1">
        
        {% include "global/partials/form.html" with title='Cadastre-se' %}
        <a class="border border-success btn btn-primary" href="{% url "authors:login" %}">Já possui uma conta?</a>
    </div>

{% endblock content %}

authors/templates/authors/pages/search.html
{% extends "global/partials/base.html" %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12 col-sm-12 my-3">
            <h3 class="text-center mb-3 card-text-color">Pesquisando por "<span class="italic">{{search_term}}</span>"</h3>
        </div>
    </div>
    <ul class="p-0">
        {% for usuario in usuarios %}
        <div class="row">
            <div class="col-12 col-sm-12 col-md-8 col-lg-6 mx-auto my-2">
                {% include "authors/partials/user_search_card.html" %}
            </div>
        </div>
        {% empty %}
        <div class="row">
            <div class="col-6 col-sm-6 text-center mx-auto card-text-color border border-warning p-2 m-2 ">
                <span>Nenhum usuário encontrado...</span>

            </div>
        </div>
        {% endfor %}
    </ul>
</div>

{% endblock content %}